name: CI and Pages

on:
  push:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff pandas

      - name: Lint with ruff (show results in log)
        run: ruff .
        # allow lint failures to not block publishing; ruff output will still appear in the logs
        continue-on-error: true

      - name: Run analysis script
        run: python execute.py > result.json

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: result.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
